### ISSUE TITLE
play-usage example linkedin not working?

### ISSUE THREAD

**Issue by bravegag** [joscha/play-authenticate#284] opened 2015-09-20 20:36 UTC
I enabled the linkedin in the play-usage example and I get the following exception/problem:

    [warn] o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: lidc="b=TB88:g=133:u=1:i=1442781238:t=1442867638:s=AQHk7D_F0kMMFibqEIOmbLzj8tb2FeEB"; Expires=Mon, 21 Sep 2015 20:33:58 GMT; domain=.linkedin.com; Path=/". Invalid 'expires' attribute: Mon, 21 Sep 2015 20:33:58 GMT

and the error message:

    oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: Service provider responded in error: 403 (Forbidden)

What's the issue? I have provided both the consumerKey and consumerSecret in the mine.conf file.

**Comment by bravegag** [comment] 2015-09-23 17:02
I tested access with a standalone example using org.scribe and it works ... it does really seem some problem/misalignment with linkedin API in play-authenticate

**Comment by dastko** [comment] 2015-10-13 12:15
I have same problem...

**Comment by akitaylor** [comment] 2015-11-09 10:55
I've also come up against this error and really seems to be the problem of the linkedin provider.
The problem is the following:
reference.conf:93 requestTokenUrl="https://api.linkedin.com/uas/oauth/requestToken?scope=r_fullprofile+r_emailaddress"

This should be modified to (or overridden in mine.conf):
requestTokenUrl="https://api.linkedin.com/uas/oauth/requestToken?scope=r_basicprofile+r_emailaddress"

**Comment by joscha** [comment] 2015-12-01 11:27
Can anyone provide a patch that does not include changing the scope?

**Comment by akitaylor** [comment] 2015-12-01 11:34
Sadly, LinkedIn changed its policy this year and this includes restricting the freely accessible profile info. To access full profile you need special login privileges:
http://stackoverflow.com/questions/30115356/is-linkedin-api-allowing-to-access-all-user-profiles

**Comment by joscha** [comment] 2015-12-01 21:01
I see. Sad times. Could you open a PR where you change the standard from
what it is to a working link?

**Comment by joscha** [comment] 2015-12-01 21:39
Fixed via #289.

**Closed by joscha** 2015-12-01 21:39 UTC
